# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    router:
        default_uri: '%env(APP_BASE_URL)%' # default base URL for generating URLs in tests (e.g. functional tests)
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
